from flask import Flask, request, jsonify
import face_recognition
import numpy as np
import cv2
import io

app = Flask(__name__)

# Load and encode known face(s) at startup
known_image = face_recognition.load_image_file("known_faces/Kian.jpg")  # put your known face here
known_encoding = face_recognition.face_encodings(known_image)[0]
known_faces = [known_encoding]
known_names = ["Kian"]

@app.route('/recognize', methods=['POST'])
def recognize_face():
    file = request.files.get('image')
    if not file:
        return jsonify({"error": "No image received"}), 400

    # Read image bytes and convert to numpy array
    img_bytes = file.read()
    img_array = np.frombuffer(img_bytes, np.uint8)
    img = cv2.imdecode(img_array, cv2.IMREAD_COLOR)

    # Convert from BGR (OpenCV) to RGB (face_recognition expects RGB)
    rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Find face encodings in the uploaded image
    face_encodings = face_recognition.face_encodings(rgb_img)
    if not face_encodings:
        return jsonify({"error": "No face found"}), 400

    # Just check the first face found
    match_results = face_recognition.compare_faces(known_faces, face_encodings[0])

    if match_results[0]:
        return jsonify({"name": known_names[0]})
    else:
        return jsonify({"name": "Unknown"})

if __name__ == '__main__':
    app.run(debug=True)
